FROM python:3.13-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copy Poetry configuration files
COPY pyproject.toml poetry.lock ./


RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --no-root

    
COPY src/ ./src/

EXPOSE 8000

# Run the script entry point
CMD ["python", "src/main.py"]